### ISSUE TITLE
Error de Servidor:

### ISSUE THREAD

**Issue by richi-alvarez** [epayco/odoo_ePayco#3]
Buenos dias.

Al tratar de realizar el pago me sale el siguiente error:
Error de Servidor:
No podemos redirigirle al formulario de pago.A journal must be specified of the acquirer ePayco. None

ya tengo configurado bien el plugin, pero no entiendo a que se debe?

![ticket](https://user-images.githubusercontent.com/39378263/69557401-86c67f00-0f74-11ea-9f97-1d4fa77c9128.png)

**Comment by mamcode** [comment]
@richi-alvarez Te hace falta configurar el diario de pago.

![screenshot-localhost_9999-2019 11 25-13_24_53](https://user-images.githubusercontent.com/334317/69563262-2b51bc80-0f87-11ea-9e50-8f4b8ef13424.png)

**Comment by richi-alvarez** [comment]
perfecto, ya esta saliendo este otro:
![image](https://user-images.githubusercontent.com/39378263/69570613-25130e80-0f8e-11ea-817a-52428d3d5495.png)

**Comment by mamcode** [comment]
@richi-alvarez Debes definirle un tipo de documento al cliente y por supuesto un numero de documento (vat).

**Comment by elMancho** [comment]
Cual es el proceso para crear dicho documento y numero de vat ?

**Comment by ACBRI** [comment]
ya somos dos con la misma duda.
