### ISSUE TITLE
Provide 13.0 compatible version

### ISSUE THREAD

**Issue by yaazkal** [epayco/odoo_ePayco#5]
Hi, Odoo 13 has been released October 2019; will be great to have this addon compatible to that version.

Thanks.

**Comment by julio-daza** [comment]
Hola! tal como @yaazkal   quisiera saber si este modulo es compatible con la V13 y la futura V14.
Por lo pronto instalare la V12.

Gracias.

**Comment by mamcode** [comment]
Hola @yaazkal @Jucema89 de momento no esta disponible este modulo en v13, no se si hay planes por parte de ePayco en hacer la migración, en cuanto sepa algo les podre comentar. Saludos.
